### ISSUE TITLE
 error TS2307: Cannot find module 'date-holidays'.

### ISSUE THREAD

**Issue by Braste** [steve-ferrero/ng-pick-datetime#5]
Highly likely not an issue with the module itself. I installed date-holidays (npm install date-holidays --save), but tsc can't find it, when i build the project. Because i only need this for the added holiday feature, maybe you could help me with it or tell me, how to disable the holiday feature.

**Comment by SabriJaA** [comment]
Hi dude,
Sorry for the late response, I try to look at that today

**Comment by SabriJaA** [comment]
@Braste 
It has to change version (0.1.2 to 0.2.1), the call is no longer the same.
I fix the problem, can you try and tell me if the correction is correct.

issue: https://github.com/steve-ferrero/ng-pick-datetime/pull/6
