### ISSUE TITLE
on cancel click it removes the current selected value 

### ISSUE THREAD

**Issue by kumararun540** [steve-ferrero/ng-pick-datetime#8]
Hi,

On popup cancel click it removes default given current date and time value. 
Any way to fix this?

**Comment by ceininger** [comment]
Hi,

Can you give us detail on how you resolved your problem for those who will be in the same situation as you ?

**Comment by kumararun540** [comment]
i just commented setMoment and momentChanged null value on cancel click. And all working fine now.  

ng-pick-datetime/dialog.component.js 

     DialogComponent.prototype.clearPickerInput = function () {
        //this.service.setMoment(null);
        //this.directiveInstance.momentChanged(null);
         this.closeDialog();
         return;
     };

**Comment by ceininger** [comment]
Ok, thank you for your reply !
